site: https://al-qaddari.vercel.app
storage:
  type: github
  path: src/content
media:
  type: github
  path: public/uploads
  url: /uploads
collections:
  - name: books
    path: books
    pattern: '*.md'
    fields:
      - title: string
      - author: string
      - description: string
      - file: string
