site: https://al-qaddari.vercel.app
media:
  output: public/uploads
  path: /uploads
collections:
  - name: books
    path: src/content/books
    pattern: '*.md'
    fields:
      - name: title
        type: string
        label: Title
      - name: author
        type: string
        label: Author
      - name: description
        type: string
        label: Description
      - name: file
        type: string
        label: File
